# Generated by Django 3.2.9 on 2021-12-18 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curriculum",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("semester_number", models.JSONField(default=list)),
                ("exam", models.BooleanField(default=False)),
                ("test", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "учебный план",
                "verbose_name_plural": "учебные планы",
            },
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("number", models.CharField(max_length=20)),
                (
                    "qualification",
                    models.CharField(choices=[("BACHELOR", "Бакалавриат"), ("MASTER", "Магистратура")], max_length=8),
                ),
            ],
            options={
                "verbose_name": "направление",
                "verbose_name_plural": "направления",
            },
        ),
        migrations.CreateModel(
            name="LessonForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name": "форма занятия",
                "verbose_name_plural": "форма занятий",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("direction", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.direction")),
            ],
            options={
                "verbose_name": "профиль",
                "verbose_name_plural": "профили",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("release_date", models.DateField()),
                ("capabilities", models.TextField(default=None)),
                (
                    "form_training",
                    models.CharField(choices=[("русский", "русский"), ("англиский", "англиский")], max_length=20),
                ),
                (
                    "language_choices",
                    models.CharField(choices=[("русский", "русский"), ("англиский", "англиский")], max_length=20),
                ),
                (
                    "type_discipline",
                    models.CharField(
                        choices=[
                            ("базовая", "базовая"),
                            ("вариативная", "вариативная"),
                            ("курс по выбору", "курс по выбору"),
                        ],
                        max_length=20,
                    ),
                ),
                ("accounting_methodological_support", models.TextField(default=None)),
                ("material_technical_base", models.TextField()),
                ("profile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.profile")),
            ],
            options={
                "verbose_name": "программа",
                "verbose_name_plural": "программы",
            },
        ),
        migrations.CreateModel(
            name="ProgramName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
            ],
            options={
                "verbose_name": "название программы",
                "verbose_name_plural": "названия программ",
            },
        ),
        migrations.CreateModel(
            name="ThematicPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("theme", models.CharField(max_length=120)),
                ("semester_number", models.IntegerField()),
                ("text", models.TextField()),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.program")),
            ],
            options={
                "verbose_name": "тематичкский план",
                "verbose_name_plural": "тематичкские планы",
            },
        ),
        migrations.CreateModel(
            name="ThematicPlanFormLesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField()),
                ("lesson_form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.lessonform")),
                (
                    "thematic_plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.thematicplan"),
                ),
            ],
            options={
                "verbose_name": "тематичкский план форма занятий",
                "verbose_name_plural": "тематичкский план форма занятие",
            },
        ),
        migrations.CreateModel(
            name="StudentMust",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                (
                    "text_choices",
                    models.CharField(
                        choices=[("знать", "знать"), ("уметь", "уметь"), ("владеть", "владеть")], max_length=8
                    ),
                ),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.program")),
            ],
            options={
                "verbose_name": "Обучающийся должен",
                "verbose_name_plural": "Обучающийся должен",
            },
        ),
        migrations.AddField(
            model_name="program",
            name="program_name",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.programname"),
        ),
        migrations.CreateModel(
            name="InternetResource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("link", models.URLField(max_length=120)),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.program")),
            ],
            options={
                "verbose_name": "интернет ресурc",
                "verbose_name_plural": "интернет ресурcы",
            },
        ),
        migrations.CreateModel(
            name="CurriculumLessonForm",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("count", models.IntegerField()),
                ("curriculum", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.curriculum")),
                ("lesson_form", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.lessonform")),
            ],
            options={
                "verbose_name": "количество часов занятия",
                "verbose_name_plural": "количество часов занятий",
            },
        ),
        migrations.AddField(
            model_name="curriculum",
            name="profile",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.profile"),
        ),
        migrations.AddField(
            model_name="curriculum",
            name="program_name",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.programname"),
        ),
        migrations.CreateModel(
            name="Competence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("cipher", models.CharField(max_length=5)),
                ("program_name", models.ManyToManyField(to="app.ProgramName")),
            ],
            options={
                "verbose_name": "компетенйя",
                "verbose_name_plural": "компетенции",
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_name", models.CharField(max_length=120)),
                ("first_name", models.CharField(max_length=120)),
                ("cathedra", models.CharField(max_length=120)),
                ("institute", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=120)),
                ("academic_degree", models.CharField(choices=[("К.Н", "К.Н"), ("Д.Н", "Д.Н")], max_length=8)),
                (
                    "academic_position",
                    models.CharField(
                        choices=[
                            ("аспирант", "аспирант"),
                            ("преподаватель", "преподаватель"),
                            ("доцент", "доцент"),
                            ("профессор", "профессор"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "academic_tittle",
                    models.CharField(choices=[("доцент", "доцент"), ("профессор", "профессор")], max_length=15),
                ),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app.program")),
            ],
            options={
                "verbose_name": "автор",
                "verbose_name_plural": "авторы",
            },
        ),
    ]
