# Generated by Django 3.2.9 on 2021-12-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="direction",
            name="qualification",
            field=models.CharField(choices=[("BACHELOR", "Бакалавриат"), ("MASTER", "Магистратура")], max_length=20),
        ),
    ]
