# Generated by Django 3.2.9 on 2021-12-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_direction_qualification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competence",
            name="name",
            field=models.CharField(max_length=300),
        ),
    ]
