# Generated by Django 3.2.9 on 2021-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_competence_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="capabilities",
            field=models.TextField(null=True),
        ),
    ]
