# Generated by Django 3.2.9 on 2021-12-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_program_accounting_methodological_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="patronymic_name",
            field=models.CharField(max_length=120, null=True),
        ),
    ]
