# Generated by Django 3.2.9 on 2022-03-29 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20220109_1323"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentmust",
            old_name="text_choices",
            new_name="must_choices",
        ),
    ]
