# Generated by Django 3.2.9 on 2022-04-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_rename_text_choices_studentmust_must_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "competence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.competence", verbose_name="компетенция"
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.program", verbose_name="программа"
                    ),
                ),
            ],
            options={
                "verbose_name": "Соответствие компетенций",
                "verbose_name_plural": "Соответствия компетенций",
            },
        ),
        migrations.CreateModel(
            name="EvaluationTools",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order_conduct", models.TextField(verbose_name="порядок проведения")),
            ],
            options={
                "verbose_name": "порядок проведения",
                "verbose_name_plural": "порядки проведения",
            },
        ),
        migrations.AlterField(
            model_name="direction",
            name="qualification",
            field=models.CharField(
                choices=[("Бакалавриат", "BACHELOR"), ("Магистратура", "MASTER")],
                max_length=20,
                verbose_name="квалификация",
            ),
        ),
        migrations.CreateModel(
            name="Literature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "literature_type",
                    models.CharField(
                        choices=[("основная", "основная"), ("дополнительная", "дополнительная")],
                        max_length=14,
                        verbose_name="литература",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.program", verbose_name="программа"
                    ),
                ),
            ],
            options={
                "verbose_name": "литература",
                "verbose_name_plural": "литература",
            },
        ),
        migrations.CreateModel(
            name="FinalControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "exam_choices",
                    models.CharField(
                        choices=[("экзамен", "экзамен"), ("зачет", "зачет")], max_length=8, verbose_name="тип экзамена"
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                ("semester", models.IntegerField(verbose_name="номер семестра")),
                (
                    "evaluation_tools",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.evaluationtools",
                        verbose_name="порядок проведения",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.program", verbose_name="программа"
                    ),
                ),
            ],
            options={
                "verbose_name": "промежуточная аттестация",
                "verbose_name_plural": "промежуточные аттестации",
            },
        ),
        migrations.CreateModel(
            name="CurrentControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="название")),
                ("score", models.IntegerField(verbose_name="количество баллов")),
                (
                    "complance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.complance",
                        verbose_name="Соответствие компетенций",
                    ),
                ),
                (
                    "evaluation_tools",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.evaluationtools",
                        verbose_name="порядок проведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "текущий контроль",
                "verbose_name_plural": "текущии контроли",
            },
        ),
        migrations.CreateModel(
            name="CriteriaEvaluationBrief",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "level_type",
                    models.CharField(
                        choices=[
                            ("отлично", "отлично"),
                            ("хорошо", "хорошо"),
                            ("удовлетворительно", "удовлетворительно"),
                            ("неудовлетворительно", "неудовлетворительно"),
                        ],
                        max_length=19,
                        verbose_name="оценка",
                    ),
                ),
                (
                    "evaluation_tools",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.evaluationtools",
                        verbose_name="порядок проведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "критерий оценивания кратко",
                "verbose_name_plural": "критерии оценивания кратко",
            },
        ),
        migrations.CreateModel(
            name="CriteriaEvaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "level_choices",
                    models.CharField(
                        choices=[
                            ("отлично", "отлично"),
                            ("хорошо", "хорошо"),
                            ("удовлетворительно", "удовлетворительно"),
                            ("неудовлетворительно", "неудовлетворительно"),
                        ],
                        max_length=19,
                        verbose_name="Оценка",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "type",
                    models.CharField(
                        choices=[("знать", "знать"), ("уметь", "уметь"), ("владеть", "владеть")],
                        max_length=19,
                        verbose_name="Индикаторы достижения компетенции",
                    ),
                ),
                (
                    "complance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.complance",
                        verbose_name="Соответствие компетенций",
                    ),
                ),
            ],
            options={
                "verbose_name": "критерий оценивания",
                "verbose_name_plural": "критерии оценивания",
            },
        ),
        migrations.CreateModel(
            name="ContenstEvaluationTools",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField(verbose_name="текст")),
                ("image", models.ImageField(null=True, upload_to="", verbose_name="картинка")),
                (
                    "evaluation_tools",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.evaluationtools",
                        verbose_name="порядок проведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "содержание оценочного средства",
                "verbose_name_plural": "содержание оценочного средства",
            },
        ),
        migrations.CreateModel(
            name="AchivementIndicator",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "achivement_choices",
                    models.CharField(
                        choices=[("знать", "знать"), ("уметь", "уметь"), ("владеть", "владеть")],
                        max_length=8,
                        verbose_name="Индикаторы достижения компетенции",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                (
                    "complance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.complance",
                        verbose_name="Соответствие компетенций",
                    ),
                ),
            ],
            options={
                "verbose_name": "Индикатор достижения компетенции",
                "verbose_name_plural": "Индикаторы достижения компетенции",
            },
        ),
    ]
