version: '3'

services:
  db:
    image: postgres:11.1-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: discipline
      POSTGRES_USER: discipline
      POSTGRES_PASSWORD: discipline
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
