version: '3'

services:
  nginx:
    image: registry.gitlab.com/atnartur.uni/discipline-program-automation/nginx:latest
    ports:
      - 80
    build:
      context: .
      dockerfile: deploy/nginx/Dockerfile
    environment:
      - VIRTUAL_HOST=app1
    networks:
      - default
      - web
    volumes:
      - static:/app/static
    depends_on:
      - app
    restart: always

  app:
    image: registry.gitlab.com/atnartur.uni/discipline-program-automation/app:latest
    restart: always
    ports:
      - 8000:8000
    build:
      context: .
      dockerfile: deploy/python/Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
    #volumes:
    #  - static:/app/static


  db:
    image: postgres:11.1-alpine
    environment:
      POSTGRES_DB: discipline
      POSTGRES_USER: discipline
      POSTGRES_PASSWORD: discipline
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
  static:

networks:
  web:
    external:
      name: web
